name: Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build app
        run: npm run build:app
